#!/usr/bin/env python3
"""Generate the Unicode 3.2 tables used by the pure-Lua SASLprep module."""

from __future__ import annotations

import argparse
import pathlib
import stringprep
import sys
import unicodedata


MAX_CODE_POINT = 0x110000
HANGUL_FIRST = 0xAC00
HANGUL_LAST = 0xD7A3
UCD = unicodedata.ucd_3_2_0
DEFAULT_OUTPUT = (
    pathlib.Path(__file__).parents[1]
    / "src/mongodb/auth/stringprep_tables.lua"
)


def ranges(predicate):
    result = []
    start = None
    previous = None

    for code_point in range(MAX_CODE_POINT):
        if predicate(chr(code_point)):
            if start is None:
                start = code_point
            elif code_point != previous + 1:
                result.append((start, previous))
                start = code_point
            previous = code_point

    if start is not None:
        result.append((start, previous))

    return result


def prohibited(character):
    tables = (
        stringprep.in_table_c12,
        stringprep.in_table_c21_c22,
        stringprep.in_table_c3,
        stringprep.in_table_c4,
        stringprep.in_table_c5,
        stringprep.in_table_c6,
        stringprep.in_table_c7,
        stringprep.in_table_c8,
        stringprep.in_table_c9,
        stringprep.in_table_a1,
    )
    return any(table(character) for table in tables)


def format_ranges(name, values):
    lines = [f"M.{name} = {{"]
    row = []

    for first, last in values:
        row.extend((f"0x{first:x}", f"0x{last:x}"))
        if len(row) == 8:
            lines.append("  " + ", ".join(row) + ",")
            row = []

    if row:
        lines.append("  " + ", ".join(row) + ",")

    lines.append("}")
    return lines


def composition_entry(code_point):
    # Hangul composition is algorithmic in mongodb.auth.saslprep. Python 3.14
    # exposes these decompositions through ucd_3_2_0 while earlier versions do
    # not, so excluding them explicitly keeps generated bytes portable.
    if HANGUL_FIRST <= code_point <= HANGUL_LAST:
        return None

    character = chr(code_point)
    decomposition = UCD.decomposition(character)

    if not decomposition or decomposition.startswith("<"):
        return None

    values = [int(item, 16) for item in decomposition.split()]

    if len(values) != 2:
        return None

    pair = "".join(chr(item) for item in values)

    if UCD.normalize("NFC", pair) != character:
        return None

    return values[0] * MAX_CODE_POINT + values[1], code_point


def render_tables():
    lines = [
        "-- Generated by tools/generate_stringprep_tables.py from Python's Unicode 3.2 data.",
        "-- Do not edit this file by hand.",
        "local M = {}",
        "",
        "M.decompositions = {",
    ]

    for code_point in range(MAX_CODE_POINT):
        if HANGUL_FIRST <= code_point <= HANGUL_LAST:
            continue

        character = chr(code_point)
        normalized = UCD.normalize("NFKD", character)

        if normalized != character:
            values = [f"0x{ord(item):x}" for item in normalized]
            entry = f"  [0x{code_point:x}] = {{ {', '.join(values)} }},"

            if len(entry) <= 100:
                lines.append(entry)
            else:
                lines.append(f"  [0x{code_point:x}] = {{")
                for index in range(0, len(values), 8):
                    lines.append("    " + ", ".join(values[index : index + 8]) + ",")
                lines.append("  },")

    lines.extend(("}", "", "M.combining = {"))

    for code_point in range(MAX_CODE_POINT):
        combining = UCD.combining(chr(code_point))
        if combining:
            lines.append(f"  [0x{code_point:x}] = {combining},")

    lines.extend(("}", "", "M.composition = {"))

    for code_point in range(MAX_CODE_POINT):
        entry = composition_entry(code_point)

        if entry is not None:
            key, value = entry
            lines.append(f"  [{key}] = 0x{value:x},")

    lines.extend(("}", ""))
    tables = (
        ("mapped_to_nothing", stringprep.in_table_b1),
        ("non_ascii_space", stringprep.in_table_c12),
        ("prohibited", prohibited),
        ("randal", stringprep.in_table_d1),
        ("left_to_right", stringprep.in_table_d2),
    )

    for name, predicate in tables:
        lines.extend(format_ranges(name, ranges(predicate)))
        lines.append("")

    lines.append("return M")
    return "\n".join(lines) + "\n"


def build_parser():
    parser = argparse.ArgumentParser(
        description="Generate the Lua Unicode 3.2 Stringprep tables."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the output differs without rewriting it",
    )
    parser.add_argument(
        "--output",
        type=pathlib.Path,
        default=DEFAULT_OUTPUT,
        help="output path (default: src/mongodb/auth/stringprep_tables.lua)",
    )
    return parser


def main(arguments=None):
    options = build_parser().parse_args(arguments)
    generated = render_tables()

    if options.check:
        try:
            committed = options.output.read_text(encoding="utf-8")
        except FileNotFoundError:
            committed = None

        if committed != generated:
            print(
                f"{options.output}: generated Stringprep tables are stale; "
                "run tools/generate_stringprep_tables.py",
                file=sys.stderr,
            )
            return 1

        print(f"generated Stringprep tables are current: {options.output}")
        return 0

    options.output.parent.mkdir(parents=True, exist_ok=True)
    options.output.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
